### ISSUE TITLE
Import-module

### ISSUE THREAD

**Issue by Res10re** [akamai/Invoke-DHCPCheckup#6]
Cannot find in PSGallery and install PS modules:

- DHCPServer
- DNSServer
- ActiveDirectory

Build and run script on non server machine Win10. 
PS version 5.1.

What am I doing wrong?

**Comment by gc-oridavid** [comment]
You can install it with RSAT:
https://learn.microsoft.com/en-us/troubleshoot/windows-server/system-management-components/remote-server-administration-tools

The PowerShell modules are included with the management tools, make sure to install the following:
- Active Directory Domain Services (AD DS) tools and Active Directory Lightweight Directory Services (AD LDS) tools
- DHCP Server tools
- DNS Server tools
