### ISSUE TITLE
What is "requires a strong user to run." exactly

### ISSUE THREAD

**Issue by TasteOfSpaghetti** [akamai/Invoke-DHCPCheckup#9]
The Usage segment outlines the following:

"Invoke-DHCPCheckup relies on the DHCP server management API and requires a strong user to run."

Could you specify exactly what permissions this is?

**Comment by gc-oridavid** [comment]
a domain admin will definitely work :)
a user in the DHCP admins group + DNS admins group should also be enough

**Comment by TasteOfSpaghetti** [comment]
Perfect. Thank you :)

**Comment by gc-oridavid** [comment]
done :)
